export const MAX_CONTENT_LENGTH = 300;
export const MAX_NAME_LENGTH = 50;
export const MAX_PROMPT_LENGTH = 150;
export const CONTENT_WARNING_THRESHOLD = 290;
export const PROMPT_WARNING_LENGTH = 140;
export const NAME_WARNING_THRESHOLD = 40;
